apiVersion: apps/v1
kind: Deployment
metadata:
  name: project4-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project4
  template:
    metadata:
      labels:
        app: project4
    spec:
      containers:
        - name: project4-container
          image: ozdemirosman/project4-devops
          ports:
            - containerPort: 8080
